### ISSUE TITLE
submodule Apps/Benchmarks reference is broken

### ISSUE THREAD

**Issue by cboulay** [labstreaminglayer/labstreaminglayer#2]

**Comment by cboulay** [comment]
@tstenner I think you need to push a local commit.

**Comment by tstenner** [comment]
Fixed, both by pushing the commit and updating the documentation on how to avoid this in the future (dacf738b0883b0f6ca74d9ac1b1cb33c450b29fb)

**Comment by cboulay** [comment]
Thanks! Those git config options are handy.
